export * from './client.js';
export * as auth from './auth.js';
export * as camps from './camps.js';
export * as registrations from './registrations.js';
export * as users from './users.js';
export * as teams from './teams.js';
export * as matches from './matches.js';
export * as news from './news.js';
export * as products from './products.js';
export * as partners from './partners.js';
export * as events from './events.js';